### PR TITLE
Harden build container

### LINKED ISSUE #416: Add relevant hardening script to our build process
Platform images are built on Ubuntu and have a [relatively straightforward hardening method](https://github.com/cloud-gov/internal-docs/blob/main/docs/runbooks/Container-Scanning/container-scanning-and-hardening.md#the-container-hardening-process) available via `usg`. Our images are currently built on `python:3.8` base image which uses Debian Linux and doesn't have as standard of a hardening script. There are roughly two paths forward:
- Rewrite our current build container to use Ubuntu as a base image (requires changes to the base Dockerfile to update all subsequent installs)
- Continue using Debian but research an acceptable hardening script

### LINKED ISSUE #418: Push images to ECR instead of Docker Hub

### PR DESCRIPTION
**Pull request by drewbo**
## Changes proposed in this pull request:
- Switch to Ubuntu 20.04 base image
- Drop chrome install (reducing image size)
- Run USG hardening script
- Push container to ECR
- Close #416 
- Close #418

## security considerations
Should be considerably more secure build environment, adds one credhub secret

### CODE REVIEW

**Comment by svenaas** [comment]
And I was there...

**Comment by apburnes** [comment]
@drewbo will we need to update the pipeline to incorporate the UA_TOKEN before it will build the image successfully?

**Comment by drewbo** [comment]
@apburnes I was just coming here to write that. I'm looking into how to supply that secret so that it isn't saved into the image (this is working correctly locally). I also will update a few dependencies to remove vulnerabilities identified in the scan prior to registering it for scanning (separate issue)

**Review by apburnes — APPROVED** [review]
🪨

**Pull request merged**
