### PR TITLE
Feat disk memory monitoring 237

### LINKED ISSUE #237: communicate disk and memory usage during a build
#### User Story

A user should be able to determine their disk/memory usage to help optimize their site builds.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] specify available disk and memory in the build log before the clone/script/build process
- [ ] disk and memory appear in the build log
- [ ] Change made live via federalist-garden-build

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

### PR DESCRIPTION
**Pull request by drewbo**
## Changes proposed in this pull request:
- Close #237 

## security considerations
Logging `psutil.disk_usage("/")` shows disk usage for the entire container (part of which is outside of the user space). Because the repo and container themselves are open source, this doesn't present an attack surface but noting for caution's sake

### CODE REVIEW

**Comment by svenaas** [comment]
Approach looks reasonable, tests pass, test coverage hasn't diminished. 

@drewbo, are there practical steps to confirm logging reports as expected in local dev environment?

**Comment by drewbo** [comment]
Possibly but it's tricky; the container is difficult to run locally because it requires so many build options and doesn't build/run on M1 chips. From within this repo, I think you can do:

```sh
docker-compose run --rm app python main.py -p '{"branch": "main", "owner": "18F", "repository": "18f.gsa.gov", "aws_access_key_id": "abcdef", "aws_default_region": "us-east-1", "aws_secret_access_key": "fghijkl", "status_callback": "", "baseurl": "", "bucket": "", "build_id": "1", "config": "", "generator": "jekyll", "github_token": "", "site_prefix": "a" }'
```
Replacing the owner/repo/generator as needed

**Comment by svenaas** [comment]
I wasn't insisting on it before this gets merged; I trust this'll get looked at in the staging environment.

**Review by svenaas — APPROVED** [review]
With @drewbo's help I got this running far enough locally to see
```
INFO [main] @branch: main @buildid: 1 @owner: 18F @repository: 18f.gsa.gov @message: CPU Percent: 10.7
INFO [main] @branch: main @buildid: 1 @owner: 18F @repository: 18f.gsa.gov @message: Memory information: {'total': 8346095616, 'available': 7160619008, 'percent': 14.2, 'used': 489185280, 'free': 3046600704, 'active': 1740111872, 'inactive': 2696626176, 'buffers': 416878592, 'cached': 4393431040, 'shared': 383561728, 'slab': 740040704}
INFO [main] @branch: main @buildid: 1 @owner: 18F @repository: 18f.gsa.gov @message: Disk usage: {'total': 62671097856, 'used': 20105678848, 'free': 39348703232, 'percent': 33.8}
```
and that is what I was hoping to see.

**Pull request merged**
